server:
  port: 50201
spring:
  main:
    web-application-type: reactive
  application:
    name: forum-user-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 用户管理
        - id: forum-user-service
          uri: http://localhost:8010/forum-user
          predicates:
            - Path=/forum-user/**

        # 权限管理
        - id: forum-auth-service
          uri: http://localhost:8000/forum-auth
          predicates:
            - Path=/forum-auth/**

        # 帖子管理
        - id: forum-post-service
          uri: http://localhost:8020/forum-auth
          predicates:
            - Path=/forum-post/**
