server:
  port: 51803

spring:
  application:
    name: forum-video

  datasource:
    url: jdbc:mysql://localhost:3306/forum_video?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  minio:
    access-key: minio123
    secret-key: minio123
    bucket-name: video
    endpoint: http://127.0.0.1:9000


#  profiles:
#    active: dev # 开发环境配置
#    ip: 192.168.200.130  # 环境ip地址
#  cloud:
#    nacos:
#      server-addr: ${spring.profiles.ip}:8848
#      discovery: # 注册中心地址配置
#        namespace: ${spring.profiles.active}
#      config: # 配置中心地址配置
#        namespace: ${spring.profiles.active}
#        file-extension: yml # data-id 后缀
#        name: ${spring.application.name} # data-id名称